---
# tasks file for centos_lynis_remove

# ===
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html
# ===

- name: ensure that lynis is removed from the centos host
  dnf:
    name:
      - lynis
    state: absent

- name: remove the lynis repository from the centos host and clean up left-over metadata
  yum_repository:
    name: lynis
    file: lynis
    state: absent
  notify: yum-clean-metadata

- name: ensure that the required dependency packages are removed from the centos host
  dnf:
    name:
      - ca-certificates
      - curl
      - nss
      - openssl
    state: absent

- name: force dnf to check if cache is out of date and redownload if needed
  dnf:
    update_cache: yes
