---
# tasks file for debian_lynis_remove

# ===
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
# ===

- name: ensure that lynis is removed from the centos host
  apt:
    name:
      - lynis
    state: absent

- name: remove the lynis repository from the debian host
  apt_repository:
    repo: deb https://packages.cisofy.com/community/lynis/deb/ stable main
    filename: cisofy-lynis
    state: absent

- name: remove the apt signing key for lynis
  apt_key:
    id: C80E383C3DE9F082E01391A0366C67DE91CA5D5F
    url: https://packages.cisofy.com/keys/cisofy-software-public.key
    validate_certs: yes
    state: absent

- name: force apt to check if cache is out of date and redownload if needed
  apt:
    update_cache: yes
